### PR TITLE
chore: add license headers and automated check

### PR DESCRIPTION
**Pull request by JulianFeinauer**
This PR adds Copyright headers for all source files from NXAI, some more detailled attribution to code that was copied from other projects, an updated LICENSE File to include the Licenses of these projects and the respective NOTICE file.

### CODE REVIEW

**Comment by richardk53** [comment]
Hi @JulianFeinauer, looks like pre-commit hooks were not installed and are failing here. 

I checked out your branch locally and tried to apply them manually. However, your license-check/config.json file seems problematic:

`Input File .github/license-check/config.json is not a valid JSON, consider using check-json`

`.github/license-check/config.json: Failed to json decode (Expecting value: line 5 column 9 (char 60))`

**Comment by richardk53** [comment]
> Hi @JulianFeinauer, looks like pre-commit hooks were not installed and are failing here.
> 
> I checked out your branch locally and tried to apply them manually. However, your license-check/config.json file seems problematic:
> 
> `Input File .github/license-check/config.json is not a valid JSON, consider using check-json`
> 
> `.github/license-check/config.json: Failed to json decode (Expecting value: line 5 column 9 (char 60))`

I fixed the issues in the config.json file and applied the pre-commit hooks manually.

**Comment by JulianFeinauer** [comment]
> > Hi @JulianFeinauer, looks like pre-commit hooks were not installed and are failing here.
> > I checked out your branch locally and tried to apply them manually. However, your license-check/config.json file seems problematic:
> > `Input File .github/license-check/config.json is not a valid JSON, consider using check-json`
> > `.github/license-check/config.json: Failed to json decode (Expecting value: line 5 column 9 (char 60))`
> 
> I fixed the issues in the config.json file and applied the pre-commit hooks manually.

Hey @richardk53 I totally missed that there are pre-commit hooks in the repo, sorry for that!
Thanks for the help and if I can support in any other way please ping me.

**Comment by richardk53** [comment]
> > > Hi @JulianFeinauer, looks like pre-commit hooks were not installed and are failing here.
> > > I checked out your branch locally and tried to apply them manually. However, your license-check/config.json file seems problematic:
> > > `Input File .github/license-check/config.json is not a valid JSON, consider using check-json`
> > > `.github/license-check/config.json: Failed to json decode (Expecting value: line 5 column 9 (char 60))`
> > 
> > 
> > I fixed the issues in the config.json file and applied the pre-commit hooks manually.
> 
> Hey @richardk53 I totally missed that there are pre-commit hooks in the repo, sorry for that! Thanks for the help and if I can support in any other way please ping me.

@JulianFeinauer No problem. There still seems the following problem, which I haven't figured out. 
```
+++ docs/conf.py
@@ -90,4 +90,4 @@
         "image_light": "_static/nxai_logo_light.svg",
         "image_dark": "_static/nxai_logo_dark.svg",
     }
-}
```

**Comment by JulianFeinauer** [comment]
@richardk53 I rebased on main and added the newline again in the file and now it seems to work with ruff : )

**Comment by richardk53** [comment]
> @richardk53 I rebased on main and added the newline again in the file and now it seems to work with ruff : )

perfect, thanks!

**Pull request merged**
